### ISSUE TITLE
CJToken contract basic audit raport 21-02-2018

### ISSUE THREAD

**Issue by krzysztofp** [connectjob/CJToken#3]
# CJToken contract basic audit raport 21-02-2018
 The purpose of this audit was to indicate the possibilities of improvements that can be done on contract implementations, check the quality of the code and general help in further development.
 
 This audit is based on quick inspection of everything till commit [d5dee880f3760e3584491a677b96a6e8a0560dc1](https://github.com/connectjob/CJToken/commit/d5dee880f3760e3584491a677b96a6e8a0560dc1).
## Table of contents
* [Disclaimer](#disclaimer)
* [Audit overview](#audit-overview)
* [Possible vulnerabilities](#possible-vulnerabilities-and-gas-optimizations)
* [Additional notes](#additional-notes)
* [Authors](#authors)

## Disclaimer:
>The audit makes no statements or warranties about utility of the code, safety of the code, suitability of the business model, regulatory regime for the business model, or any other statements about fitness of the contracts to purpose, or their bug free status. The audit documentation is for discussion purposes only.

## Audit overview:
There are possible security vulnerabiliities. The newest version of standard used seems to be 0.4.15 and still it has a lot of fixed bugs, not to mention about other files that use 0.4.4. Could not run tests using newer versions of solidity. Outdated version of SafeMath is in use.

## Possible vulnerabilities and gas optimizations
- Use newer solidity standard, since 0.4.15 there was 26 bugs fixed, not to mention about bugs fixed since 0.4.4 (it's still used in some of your contracts)
- No need to have initialSupply in CJToken as it is overriding totalSupply
- Fallback function should not execute that much code
- There's possibility of fallback function failing due to limits of fallback functions
- Possible vulnerabilities in buyTokens function
- Multiplying by 0 may break `getTokenAmount` in `Crowdsale` contract (weiAmount parameter might be 0, but not in current implementation, used in `buyTokens`)

## Additional notes:
- Use view instead of constant (constants were replaced by view keywords in Solidity [0.4.17](https://github.com/ethereum/solidity/releases/tag/v0.4.17) release)
- Could not run tests on newer solidity compiler versions

## Authors
 - Jerzy Spendel [https://github.com/jerzyspendel](https://github.com/jerzyspendel)
 - Chris Parjaszewski [https://github.com/krzysztofp](https://github.com/krzysztofp)
 - Dawid Ryguła [https://github.com/Dawid-Rygula](https://github.com/Dawid-Rygula)

## Contact
hello@skygate.io

**Comment by Hasanyeach** [comment]
Bagaimana caranya untuk memulai
# newbie
